<a href="https://colab.research.google.com/github/alyonavyshnevska/pyTorch_playground/blob/master/pytorch_basic_toturial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Tutorial
[Link](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [0]:
import torch
from __future__ import print_function

In [3]:
x = torch.zeros(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# Construct a randomly initialized matrix
x = torch.rand(5,3)
print(x)

tensor([[0.2436, 0.6578, 0.3013],
        [0.0919, 0.5264, 0.8943],
        [0.8235, 0.5222, 0.1286],
        [0.5562, 0.2353, 0.2720],
        [0.0345, 0.5025, 0.7611]])


In [5]:
# Construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, 
# e.g. dtype, unless new values are provided by user
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
# Size
print(x.size())
# torch.Size is in fact a tuple, so it supports all tuple operations.
y = torch.rand(5,3)
print(x+y)
#print(torch.add(x,y))

# Addition: providing an output tensor as argument
result = torch.zeros(5,3)
torch.add(x,y, out=result)
print(result)

#In-place
y.add_(x)
print(y)

torch.Size([5, 3])
tensor([[1.5349, 1.9286, 1.4384],
        [1.6188, 1.1579, 1.0270],
        [1.3413, 1.0555, 1.4390],
        [1.1197, 1.1898, 1.9325],
        [1.6060, 1.4790, 1.9386]], dtype=torch.float64)
tensor([[1.5349, 1.9286, 1.4384],
        [1.6188, 1.1579, 1.0270],
        [1.3413, 1.0555, 1.4390],
        [1.1197, 1.1898, 1.9325],
        [1.6060, 1.4790, 1.9386]])
tensor([[1.5349, 1.9286, 1.4384],
        [1.6188, 1.1579, 1.0270],
        [1.3413, 1.0555, 1.4390],
        [1.1197, 1.1898, 1.9325],
        [1.6060, 1.4790, 1.9386]])


In [8]:
#Any operation that mutates a tensor in-place is post-fixed with an _. 
# For example: x.copy_(y), x.t_(), will change x.
y.t_()

tensor([[1.5349, 1.6188, 1.3413, 1.1197, 1.6060],
        [1.9286, 1.1579, 1.0555, 1.1898, 1.4790],
        [1.4384, 1.0270, 1.4390, 1.9325, 1.9386]])

In [9]:
# Use standard NumPy-like indexing
print(y[:,0])

tensor([1.5349, 1.9286, 1.4384])


In [10]:
# Resizing
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
# one element tensor can be accessed via .item()
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7628])
0.7628363370895386


In [12]:
# Convert a torch tensor to numpy
torch_tensor = torch.randn(2,2)
numpy_array = torch_tensor.numpy()
print(numpy_array)

# Numpy array automatically updates
# if chnages are made to tendor value
torch_tensor.add_(200)
print(numpy_array)

[[-1.7632116  -0.7176378 ]
 [-1.3597999   0.34305292]]
[[198.23679 199.28236]
 [198.6402  200.34305]]


In [13]:
# Numpy to torch tensor
import numpy as np
nump = np.ones((2,3))
tor = torch.from_numpy(nump)
print(tor)

# tensor also automatically updates
# if changes are made to a numoy array from which it was constucted
np.add(nump,200,out=nump)
print(tor)

# All the Tensors on the CPU except a CharTensor support converting to NumPy and back

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[201., 201., 201.],
        [201., 201., 201.]], dtype=torch.float64)


In [16]:
# CUDA tensors
# CUDA is a parallel computing platform and programming model 
# for general computing on GPUs

if torch.cuda.is_available():
  print("GPU available")
  device = torch.device("cuda")     # cuda device object
  y = torch.ones_like(x, device=device)   # directly create a tensor object on GPU
  x = x.to(device)
  z = x+y
  print(x,y,z)
  print(z.to("cpu", torch.double))    #.to can change dtype

GPU available
tensor([0.7628], device='cuda:0') tensor([1.], device='cuda:0') tensor([1.7628], device='cuda:0')
tensor([1.7628], dtype=torch.float64)
